
// Font into Base64 HelveticaThin.ttf
const FontInBase64 = "AAEAAAAPAIAAAwBwRkZUTU5xNrYAAGI0AAAAHEdERUYC/QHSAABaPAAAADhHUE9T1NUA1wAAW0wAAAboR1NVQtWK2DQAAFp" +
    "0AAAA2E9TLzJriNOFAAABeAAAAGBjbWFwDFSlYQAABYAAAAI6Z2FzcP//AAMAAFo0AAAACGdseWYoupIIAAAJlAAAQ2BoZWFkA/Y09AAAAPwAAAA" +
    "2aGhlYQcHBEwAAAE0AAAAJGhtdHjslCSbAAAB2AAAA6hsb2NhteulqgAAB7wAAAHWbWF4cAEzAFUAAAFYAAAAIG5hbWXAaFelAABM9AAAB4Bwb3N" +
    "0rZp5DgAAVHQAAAXAAAEAAAABAACv0SxfXw889QALA+gAAAAA0Hf4rAAAAADQd/is/9z/KgQLA40AAAAIAAIAAAAAAAAAAQAAAsr/SABTBDL/3P/" +
    "nBAsAAQAAAAAAAAAAAAAAAAAAAOoAAQAAAOoAUgAHAAAAAAACAAAAAQABAAAAQAAAAAAAAAACAZ4AZAAFAQACvAKKAAAAjAK8AooAAAHdADIA+gA" +
    "AAgAFAwQAAAIABIAAAgsQAABIAAAAAAAAAABQWVJTAAAAIOABAsr/SABTA40A1gAAAAQCAAAAAgACyAAAACAABAPoAAAAAAAAAU0AAAEWAAABAwB" +
    "qATsARAIsABECLAAQAwoALAJRACkAzABSAPEARADxAAoBYAAdAlgAOAEWAGQBYABFARYAcgFN//YCLAAcAiwAbAIsAC4CLAAkAiwAIAIsACUCLAA" +
    "rAiwAOAIsACMCLAAiARYAcgEWAGQCWAA3AlgANwJYADgCBwArAyAAGwJR//MCdgA+AsAAJwKbAEACMAA6AgIARgLlACYCngBAAKoAQAHhABcCZQA" +
    "9AfQAPQMpAD8CpgA7AuUAIAJPAEIC5QAgAnYAQAJ2ACgCB//xAqAAOgIs//EDef/5Aiz/7wI+/+oCGf/9APEAXgFN//YA8QAKAlgAdAH0AAAAp//" +
    "fAfQAHgIsADoCBwAkAiwAIgIHACEA8QADAhkAIQIHADoAqABAAKj/3AHPADkAqABAAxwAOwIHADkCGQAfAiwAPgIsACMBFgA3AeEAIQEDAAACBwA" +
    "3Abz//gLA//wBvP/5Abz/9wGqAAkBTQAKAN4AXQFNAAoCWAAqAiwAKwIsADkA3gBcAiwAMgMgACIBhQBCAlgANwGQABABkAA7AlgANAIHADsCWAA" +
    "7ARYAagGFAE8CWAAwAiwACQIwADoCwP/8AfQAQwLAAB8CdgAoAKoAQACq/+kB4QAXA+gADwPoAD8CwP/0AmUAPQIs//QCngA/AlH/8wJ2AD8CdgA" +
    "+AfQAQwKeAAoCMAA6A9T/8AJ2ACgCngBAAp4AQAJlAD0CngATAykAPwKeAEAC5QAgAp4AQAJPAEICwAAnAgf/8QIs//QC0gAdAiz/7wKtAD8CdgA" +
    "/A+gAPwQAAD8DCv/7AykAPwJRAD8CwAAfA9QAQAJ2/+0B9AAeAhkAKgH0ADUBkAA8AhkABwIHACEC0v/1AdkAHQIHADgCBwA4Ac8AOQIZABECdgA" +
    "4AgcAOAIZAB8CBwA4AiwAPgIHACQBvAAIAbz/9wL+ACQBvP/5AhkANwHpADYDAAA3AxUANgJj//8CdgA2AekANgIHAB8C2gA4AfT/+wIHACECBwA" +
    "AAZAAOQIHACUB4QAhAKgAQACo/+gAqP/cAwoAEQMKADcCBwAAAc8AOQG8//cCBwA4AfQAPwGQADkB9AAAA+gAAADMAE0AzAA/AMwAPQE7AEYBOwA" +
    "2ATsANgIsADUCLAA1AfQASAPoAI0EMgAsAQMAQAEDAFEDtgBBA94AagJ/AA4CWAAYAtIALwJYACoCWAA0AlgANAJYADQBYABFARYAAAAAAAMAAAA" +
    "DAAAAHAABAAAAAAE0AAMAAQAAABwABAEYAAAAQgBAAAUAAgB+AKQApwCpAKwArgCxALcAuwD3AZIEDARPBFwEXwSRIBQgGiAeICIgJiAwIDohFiE" +
    "iIgYiGiIeIkgiYCJl4AH//wAAACAAowCmAKkAqwCuALAAtQC7APcBkgQBBA4EUQReBJAgEyAYIBwgICAmIDAgOSEWISIiBiIaIh4iSCJgImTgAP/" +
    "//+P/v/++/73/vP+7/7r/t/+0/3n+3/xx/HD8b/xu/D7gveC64LnguOC14KzgpN/J377e297I3sXenN6F3oIg6AABAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBgAAAQAAAAAAAAABAgAAAAIAAAAAAAAAAAAAAAAAAAA" +
    "BAAADBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlN" +
    "UVVZXWFlaW1xdXl9gYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhqAGJl2m0AaWbgAADlAADja+bnAGwAAAAAAAAAAAAAAABo4nH" +
    "k4Wdv2wAAAAAAANDR1dbS03AAAAAAAN3eAADZbtTX3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWACoAWACoAPgBTgF" +
    "cAXIBiAGmAboBzgHcAegB+AIuAkYCgAK6AtwDCANCA1oDngPSA+QD/gQQBCQEOARsBM4E9AUmBU4FbAWGBZwFzgXoBfYGFAYwBkAGbgaSBroG5Ac" +
    "WB1gHoge0B9IH7ggeCDwIXAh4CIoImAiqCL4IygjYCSoJVAl8CagJ0gn4CjQKWgpuCowKqgq4CuoLCgswC14LhguiC/IMHAw6DFYMiAyiDM4M5g0" +
    "mDTQNdg2kDf4OOA5KDrIO+g8WDyYPcA+SD64P0g/uD/oQFhAwEHAQlBDAENgRBhFQEV4RdhGUEdQSBhIyElQSihKgEsYS8BMiEzQTVhNwE5wT1BP" +
    "uFBoUNhRcFIoUpBTMFOAVChUyFUQVaBWcFboV0hXyFgoWKBZSFoAWqBbWFwgXMBeCF8YX+hgKGC4YWBh+GLYY0Bj8GRQZMhlQGWYZjBmgGc4Z9ho" +
    "IGjQagBqaGrIa0hrqGwgbKhtQG3AbnhvOG/YcLBxgHHgcphz2HQodIh1AHW4dlh26HdoeGB4uHkAeVB5iHnAehB6YHqwezh7wHxIfKB9GH1wfdB/" +
    "eH/AgAiA4IF4gdiCOIPghTCFuIYghoiGwIbAAAAACAGoAAACZAsgABQAJAAATFQMjAzUTFSM1lwcdBy0vAsjI/rQBTMj9mmJiAAIARAGaAPYCrQA" +
    "DAAcAABMjAzMTIwMzZh0FJ4YdBScBmgET/u0BEwACABEAAAIWAq0AGwAfAAAzIzcjNTM3IzUzNzMHMzczBzMVIwczFSMHIzcjPwEjB4ckKHqAInm" +
    "AKSQqnCojKXmAInl/KCQonKIjnCLYIroh2NjY2CG6ItjYIrq6AAMAEP+YAhIDCAAoAC4AOAAAARUzMhYdASM0JicRFhUUBisBFSM1Jj0BMxQGFRQ" +
    "WFxEuAzU0Njc1GQEOARUUFxE+ATU0LgMBHwJmcihWXPODbgIc8ykBamEuQEUkdmFSXctYchojPisDCEtkWghRTwT+2CKgWGlYWAXTCQMJAVxRBQF" +
    "ACRQnQy5QZAJL/nEBIQRMQHxC/sYCS1MgMx0ZCgAFACz/6ALjAsYAAwAOABoAJQAxAAAJASMBAzIWFRQGIiY1NDYBMhYVFAYjIiY1NDYBIgYVFBY" +
    "zMjY0JgEiBhUUFjMyNjU0JgJx/kUkAbwORl1bklte/tdIXFxISVtdAbQ1SUk4NklK/lo3SEg4N0lJAsb9IgLe/o9jS1BlY05NZQFnYk1PZGNPTGT" +
    "+elM9QlRVflMBZ1I/QVNVQD9RAAAAAwAp//ICVALDACIALgA6AAABBgcXIycGIyImNTQ+AjcuAzU0NjMyFhUUDgIHFzY3JzY1NCYjIgYVFB4BFw4" +
    "DFRQWMzI2NwIEAyJ1M1dLhFx2ID02JxgUJRBWREBUGDYjJKoWA9mEQC8xQSUcECQtOR1iSThfHwEmT0mOa3loUSZEOSUWHBk2Lxc9TEw6ITczGhj" +
    "TPTx1SlUsOzosGEQkThUeMjsiQVc+NwAAAAEAUgGaAHkCrQADAAATIwMzdB0FJwGaARMAAAABAET/SADnAtAACgAAEw4BFRQXIyY1NDfnOkF7I4C" +
    "AAtBg8Hfi3+Hj6toAAAEACv9IAK0C0AAKAAATFAcjNjU0JiczFq2AI3tBOiOAAQzj4d/id/Bg2gAAAQAdAcABQwLWAA4AAAEHFwcnByc3JzcXNTM" +
    "VNwFDfU4XTVAYUHsJex17AmMpaRFpZxFnKRsqgoIqAAAAAQA4AB0CIQH/AAsAACU1IzUzNTMVMxUjFQEb4+Mj4+Md4SHg4CHhAAEAZP+AAKQAZgA" +
    "JAAA3FRQGBzU2NyM1pBknIQEUZlU2ShEiFUlmAAABAEUA+wEbASIAAwAAARUjNQEb1gEiJycAAAAAAQByAAAApABmAAMAADcVIzWkMmZmZgAAAf/" +
    "2//cBWALOAAMAAAkBIwEBWP7CJAE/As79KQLXAAACABz/8QIQArwAEgAkAAABMh4DFRQOAiMiJjU0PgIXIgYVFB4DMzI+AjQuAgEWOVo2JA0XNmd" +
    "IeIAXNGdIY24KHC1LMT1YKxIRK1cCvCxGYF80Q3VuQLOoQ3dyRCavnSxQVT0nPGVncmZlPAABAGwAAAFNArAACgAAAREjEQ4BBzU+ATcBTSorUDx" +
    "FTSsCsP1QAmYrJgciDzM+AAABAC4AAAH5ArwAJQAAJRUhPgE/AT4ENTQmIyIGByM2NT4BMzIWFRQGBwYHDgMHAfn+NQZTTT4iIjodGFxPXVYCKQE" +
    "EdGdgcj46Kk4oHDsdBiUlTWo0KhgYMyk8IEdUcV8JDGZ5aFZAYS4hNRsVMzIfAAAAAAEAJP/xAgECvAApAAATPgEzMhYVFAYHHgEVFAYjIiY9ATM" +
    "VFBYzMjY1NCsBNTMyNjU0JiMiBgc2AnhqYHVPO0VXg2pugidrX1Zt0RccWWFeT1liAwHXbHliUD9UBwtXS150eGYUDlpmX0ueIkdDQU5jXgAAAgA" +
    "gAAACBgKyAAoAEQAAJRUjFSM1ITUBMxEjETQ3BgcDAgZxKP6zAU0oKAErBfvTI7CwKQHZ/iEBVzEmQwf+nAAAAAABACX/8QH9Aq0AGgAAARUhAzY" +
    "zMhYUBiMiJiczHgEzMjY0JiMiBycTAd7+wDk9cmWEh2dqfgInA2VbVm9wVnA9J0cCrSb+8lSGzoh5Z1Voc7BzXgEBYAAAAgAr//ECCAK8ABwAJwA" +
    "AASMuASMiDgMVPgEzMhYVFAYjIicmNTQ2MzIWByIGFRQWMjY1NCYB+ikIYEQ1Ty0bCBluTGKChmWAQTGCeVdy01Fvb6ZubwIGQFMxSWdXMEZPhWR" +
    "lh2ZNmrnFZLVyVFV0c1VWcQABADgAAAHzAq0ACgAAARUGAgcjNhI3ITUB84SeBSsEqIH+agKtKIL+o6aoAWp1JgADACP/8QIIArwAFgAiAC4AABM" +
    "mNTQ2MzIWFRQGBx4BFRQGIyImNTQ2EyIGFRQWMzI2NTQmAyIGFRQWMzI2NTQmwYFzY2RyRzlGVoBwcoNYmlJaXVFQXFtUXWprX11qawF1HntRXVt" +
    "RPVENCl1KYnFvYEtfAS5JQkBISUBCSP7MV0xRXF1QTVYAAgAi//ECAQK8ABgAIgAANzMeATMyNj0BBiMiJjU0NjMyFxYVECMiJhMiBhQWMjY1NCY" +
    "1KAtfRGRrO5djg4VkfkI291Z1zFFvbqZvcKNBTameJpqEZGWHYVCg/oZhAkZyqnBxVVRyAAACAHIAAACkAgAAAwAHAAA3FSM1ExUjNaQyMjJmZmY" +
    "BmmZmAAACAGT/gACkAgAACQANAAA3FRQGBzU2NyM1ExUjNaQZJyEBFDIyZlU2ShEiFUlmAZpmZgAAAQA3ADICIAHrAAYAADc1JRUNARU3Aen+QQG" +
    "//CTLJLm3JQAAAgA3AKACIAF4AAMABwAAEzUhFQU1IRU3Aen+FwHpAVchIbchIQAAAAEAOAAyAiEB6wAGAAAlBTUtATUFAiH+FwHA/kAB6fzKJbe" +
    "5JMsAAAACACsAAAHQAtcAHQAhAAATNDYzMhYVFA4CBw4BFSM1NDY3PgI1NCYjIgYXExUjNStua1txEC0ZIy4WJx8yIyIlXEhZWQHELgHrZYdkTyE" +
    "2OBkgKzZIC0VELyEkRSM/UXVT/ntmZgAAAAIAG//zAwEC1AA4AEYAACUXDgEjIiY1NDYzMhYVFAYjIiY1NDcGIyImNTQ2MzIWFzczBwYVFBYzMj4" +
    "BNTQmIyIGFRQeATMyNgM0JiMiBhUUFjMyNjc2AsQPTI5YpeHxqI3AcFkfKgg0Yj9GclM3QgMfIzsZHhcyTyW0f57fZ6NhU4VvNS9FXjQxNkoUDm4" +
    "UNTLDoKnVn4depSQeBihwVT9Wlz81Z79WGBYXUWkwfozJmmSZTC8Bai89i0ozRFU8LQAAAAAC//MAAAJdAsgABwARAAAJASMnIQcjARMDLgEnDgI" +
    "HAwFCARswWf6pWy8BIbKCBREEAwsJBIUCyP045uYCyP5CAUoMNAsIHRgL/rMAAwA+AAACVQLIAA8AFwAeAAATITIWFRQGBx4BFRQHBiMhExEzMjU" +
    "0JiMDETMyNTQjPgElXH5LPkhZUz10/u0r4MlpUu7l3NYCyFpXPlkLCF5JZzcoAqP+4I9MRf68/sehmAAAAAEAJ//wAqEC2QAYAAABDgEjIiY1NDY" +
    "zMhYXIy4BIyIGEBYzMjY3AqEKqoCTs7eUbKwMKhOIYYCenIBxjA0BFIKiy6eoz39oWWe5/tS3jnAAAgBAAAACdALIAAgAEAAAEzMyFhUUBisBExE" +
    "zIBE0JiNA8J6mn6TxK7cBJ4yPAsi4oabJAqL9hAFGkKYAAQA6AAACHgLIAAsAAAEVIREhFSERIRUhEQIa/ksBmv5mAbn+HALIJv7jJv7HJgLIAAA" +
    "AAAEARgAAAgYCyAAJAAABFSERIRUhESMRAgb+awFs/pQrAsgm/uIl/qECyAAAAQAm//ACqwLXACAAAAERIyc3DgEjIiY1NDYzMhYXIy4BIyIGFRQ" +
    "WMzI2PQEhNQKrHwYBHJdelrq6lnGoECkTjl+FoKGFepT++QFc/qR/LlpjyqKp0oJqW2u7mpO0mX4MJAAAAAEAQAAAAl8CyAALAAABESMRIREjETM" +
    "RIRECXyv+NysrAckCyP04AWH+nwLI/r8BQQAAAAABAEAAAABrAsgAAwAAExEjEWsrAsj9OALIAAAAAQAX//ABowLIABEAAAERFCMiJjU0NzMVFBY" +
    "zMjY1EQGjxWpdASlDWlZEAsj9+dFsag4NFVxbWlUCBAAAAQA9AAACdwLIAAsAAAkCIwEHFSMRMxEBAmP+uAFcN/68lCsrAcICyP7Y/mABg4f8Asj" +
    "+ZwGZAAABAD0AAAH/AsgABQAAJRUhETMRAf/+PiwnJwLI/V8AAAEAPwAAAuoCyAAZAAABESMRNDcOAQcDIwMmJxYVESMRMxMXNjcSNwLqKgYGFAb" +
    "7KvwCHwUqPOM4EiCkQwLI/TgCFUVGDjgO/bQCRQRVcxb96wLI/fCLM0oBgZ0AAQA7AAACYALIABEAAAERIwEmJxYVESMRMwEWFyY1AwJgMf5xJxc" +
    "DKjIBhyEkAwECyP04AjQ4KhtS/dcCyP3WMDtDRQINAAAAAgAg/+8CxQLZAAoAFwAAATIWFRQGICY1NDYXIg4BFRQWMzI2NTQmAXGXvbz+0Lm7llu" +
    "IQqKDhKSlAtnSqKXLzaimzyZflVmXuriUlrwAAAACAEIAAAI/AsgADAAZAAATITIXFhUUBwYrAREjExEzMjc2NTQnLgIjQgEVZzFQSjha9isr3VY" +
    "pSz8UMCEgAsghNm5pNin+xQKi/r4YLF1cKQ0NAgACACD/3wLHAtgAEAAgAAAFBycGIyImNTQ2MzIWFRQGByc2NTQmIyIGFRQWMzI3JzcCxxZ1UHi" +
    "cuLyXlbw4MyFgo4KEo5yMYEZwFwUcVEPQn6jRzqRVlTIZaZqTuLqWjr02Tx0AAgBAAAACVQLIAB0AKgAAEyEyFxYVFAYHHgEXHgEXFhcjJicuAic" +
    "uASsBESMTETMyPgM1NCcmI0ABJWA0T1JFN0IKBgYHAwswBgQCBAMBB1tn3Ssr1yQ6PCgZQS5XAsghNWdHXg0JLzYghyIPEwkUDjpCCF46/rkCo/7" +
    "IBxQiOidWKBwAAQAo//ECTQLXADUAAAEjJiMiBhUUHgMXFhceBhUUBiMiJjUzHgEzMjY1NC4GJyYnJjU0NjMyFgI7KwvVXmoWJDo9KRYLIh09His" +
    "VEI59g5cpAn9yaXYOEyUcMxo3CW8kZINzdYwB/bRPRh8uHhcPCQQDCAcTEB4hMR1fbH59bGtXThcmHBgODwYMAhoQLWhXZWwAAAH/8QAAAhUCyAA" +
    "HAAABFSMRIxEjNQIV/Cv9Asgm/V4CoiYAAAEAOv/xAmACyAAQAAABERQGIyAZATMRFBYzMjY1EQJgkX3+6CxufnppAsj+K3mJASYBsf5NfoGEewG" +
    "zAAH/8QAAAjoCyAALAAAJASMBMxMeARc2NxMCOv73Mv7yMNUIGAMFHdMCyP04Asj9xhRLCRVRAjwAAf/5AAADfQLIABgAAAEDIwMmJwYHAyMDMxM" +
    "WFzY3EzMTFhc2NxMDfcwxpxUJCRajMc8unRUJBRmhNaUQDgkTnQLI/TgCMkYoJkr90ALI/d5JLx9XAiT91zY7MUACKQAAAf/vAAACOwLIAAsAAAE" +
    "DASMLASMBAzMbAQIu/gELNfHzMwEM/TTj6ALI/qb+kgFN/rMBbgFa/sUBOwAAAf/qAAACVALIAA4AAAkBESMRATMTFhc+AjcTAlT+4Cv+4TTiEg4" +
    "DDAoF5QLI/mH+1wEpAZ/+uBoYBRQQBwFKAAH//QAAAhkCyAAMAAABFQEhFSE1ASIGIyE1AhD+HAHt/eQB5AsZG/55Asgq/YgmKwJ3AScAAAAAAQB" +
    "e/0gA5wLRAAcAABMVIxEzFSMR52JiiQLRIfy5IQOJAAAAAf/2//cBWALOAAMAAAUjATMBWCT+wiMJAtcAAAEACv9IAJQC0gAHAAATESM1MxEjNZS" +
    "KY2MC0vx2IQNHIgAAAAEAdAESAeUCrQAGAAAbATMTIwsBdKUnpSeSkQESAZv+ZQF0/owAAAABAAD/gwH0/7UAAwAAFTUhFQH0fTIyAAAB/98CVAC" +
    "MAuAAAwAAExcjJxN5JocC4IyMAAAAAgAe//IB8wIOACoAOAAAJRUGIyImPQEOASMiJjU0Nz4BNzY1NCYjIgcjPgEzMhceAhURFB4CMzIDBgcOAQc" +
    "GFRQWMzI2NQHzERgiGSFeSVBZxGcyCgdKR48MJgVmWmcxDg4BAQcQDQpWDxQfnig8SD1SbSQgBiUxGUA7TEONEAgLEAsqOjyJU1g3EC0cHv73Dw4" +
    "SCAECDQYKEBIbQzQ8Zk0AAAACADr/8AIHAsgADQAZAAATETYzMhYUBiMiJxUjERciBhUUFjMyNjU2JmIzkGh6emiVMCbkVWdoV1ZnAWgCyP6/ipP" +
    "6lIt7AsjagWttg4Btb4AAAAABACT/8QHpAg8AGQAAJQ4BIyImNTQ2MzIWFyMuASMiBhUUFjMyNjcB6QxzW3B7g21ZbgopCFpFW21qV0pfCrRcZ5l" +
    "0fZRbUT9LgWxrglZLAAIAIv/wAfACyAAPABoAAAERIzUOASMiJjQ2MzIWFxEHIgYUFjMyNjU0JgHwJhNoSGp7fWhGZBfAVmZlWFlnYQLI/Th9Q0q" +
    "R+pVHPwE+24HcfoBuY4oAAAACACH/7wHqAg4AEwAZAAAlDgEjIiY0NjMyFh0BIRQWMzI2PwE0JiIGBwHlDnRZan+BaGx0/mFhX0ZdDwRfsF4JrlZ" +
    "pkvSZmHAOYYZSS21VenRbAAABAAMAAAD+AswAGgAAExUmIyIOAxUUHQEzFSMRIxEjNTM1NDYzMv4fCRggEQgBa2soWVkvSQwCySQDDhAlFxgHAyw" +
    "j/iMB3SNARUcAAgAh/z0B4QIOABwAJwAAAREUBwYjIiYnMx4BMzI3Nj0BBiMiJjU0NjMyFzUHIgYUFjMyNjU0JgHhHTOOXGgGKQRYR2gtIDGPY3Z" +
    "7ZYc0ulRkYlNbYGUCAP4pXzNaUUw9PjwsYWyDiHF2joN1FnfIdn9fYXYAAAAAAQA6AAAB0ALIABYAABMRBz4BMzIWFREjETQmIyIGBwYVESMRYgE" +
    "WXUVbXChJTkBWEAkoAsj+5SE7Rmpb/rgBQk1cTT8kN/78AsgAAAIAQAAAAGgCyAADAAcAABMVIzUXESMRaCgoKALIZWXI/gACAAAAAAAC/9z/RQB" +
    "pAsgADAAQAAATERQGIyInNTMyNjURNxUjNWkwRQQUFDEgKCgCAP3KSD0CIik1AjnIZGQAAAABADkAAAHjAsgADgAAAQcTIwMHFSMRMxE+ATclAdT" +
    "h8DPbdCgoBxsHARMCAL/+vwElY8ICyP4oBhkG6wABAEAAAABoAsgAAwAAExEjEWgoAsj9OALIAAAAAQA7AAAC5QIOACEAABMVPgEzMhc2MzIWFRE" +
    "jETQjIgcGFREjETQnJiMiBhURIxFhFVU9dSA0ck1VKIJCJy4oDx1QSVQoAgBoNUFubltK/pcBWo8pL1b+xQFSPB49alz+3QIAAAEAOQAAAdECDgA" +
    "SAAATFTYzMhYVESMRNCMiBwYVESMRYDiFVV8olWUxHSgCAHF/ZVn+sAE8rlQzWv73AgAAAAACAB//8QH6Ag8ACwAXAAABMhYVFAYjIiY1NDYXIgY" +
    "VFBYzMjY1NCYBDmuBgWxtgYNrWG1rW1hqagIPlX17kZN8epUjgmpsgH9qbYIAAgA+/0cCCAIOAA8AHAAAExU2MzIWFRQGIyImJxEjERciBhUUHgE" +
    "zMjY1NCZkMo1ofX1nR2QTKONZZCVZQFVnZgIAeoiVfHqVRkD+0wK5FH9xP2dGgmtugQAAAAACACP/RwHuAhAADgAYAAABESMRBiMiJjU0NjMyFzU" +
    "GIgYVFBYyNjU0Ae4oMo9ne31pizRmsGZmrmcCAP1HAS6Eknt9lYh4E4FvbH5/bHAAAAEANwAAASYCBAAOAAABFSMiBw4BHQEjETMVPgEBJg9ZNBw" +
    "PKCccXgIEKUUlVT/dAgCHSkEAAAAAAQAh//ABvAIOADwAAAEjLgEjIgYVFB4IFx4EFRQGIyImNTMUFjMyNjU0LgMnJicuCDU0NjMyFgGtKQZPSUB" +
    "LBQcQChkMIA0lBiUgQB8ab1thcChZUkdZFRgxGRsJBAcpFCYUHhARB2NYWWcBa0Q8Ni4MFA8PCQsFCAQIAQgJGRswH0RTY1lMTD4zFiMVEwYGAgE" +
    "CCQQLCg8TGB4SQUpTAAEAAP/9APUCoQAdAAATFSMRFB4DMzI3FQYjIi4DNTQ1ESM1MzUzFfVuAQYOGxQRGR0THigVCgFfXygCACP+pRcRIA0LBCU" +
    "EEBMrHB8IBAFLI6GhAAEAN//xAcoCAAARAAABESM1BiMiJjURMxEUMzI2NREByiY2gllcKJVWWAIA/gBse2pbAUr+v6t9WQEWAAH//gAAAb8CAAA" +
    "LAAABAyMDMxMeARc2NxMBv8Iv0CyTCBwFDRyGAgD+AAIA/pgVTQ4mTAFmAAAAAf/8AAACwQIAABkAAAEDIwMmJwYHAyMDMxMWFz4BNxMzExYXNjc" +
    "TAsGlLnkNCA8GejClLHcCGAUQBXQydAYUEQh4AgD+AAGFKSM5Ev56AgD+igdXEEAQAXT+ihRJRBcBeAAAAAH/+QAAAcQCAAALAAABBxMjJwcjEyc" +
    "zFzcBsLnNNLO0MMu7NKCjAgDy/vLw8AEM9NbWAAAB//f/SAG/AgAAGAAAAQMOAyMiJzUWMzI2NzY3AzMTFhc2NxMBv90PDyAtIRUSEBEkKg8YC9k" +
    "tqQgPEwWYAgD9yycgLBACJAMfJDccAf/+bxMtOA0BjAAAAQAJAAABoAIAAAkAAAEVASEVITUBITUBkf6lAWr+aQFX/sICACH+RCMmAbcjAAAAAQA" +
    "K/0cBRQLTACwAAAUiJy4CPQE0Jic1PgE9ATQ+ATc2MxUGBwYdARQOAwceBB0BFBcWFwFFSi0ZGQQ4VlY4BBkZLUpcHw8CDRkxJCQxGQ0CDx9cuSY" +
    "VRDEsRk0+DBoMPk1GLDFEFSYaBEEfTykoKj4gHAQEHCA+KigpTx9BBAABAF3/KgCBAxIAAwAAFxEzEV0k1gPo/BgAAAAAAQAK/0cBRQLTACwAAAE" +
    "OAR0BFA4BBwYjNTY3Nj0BND4DNy4EPQE0JyYnNTIXHgIdARQWFwFFVjgEGRktSlwfDwINGTEkJDEZDQIPH1xKLRkZBDhWAQAMPk1GLDFEFSYaBEE" +
    "fTykoKj4gHAQEHCA+KigpTx9BBBomFUQxLEZNPgwAAAAAAQAqANECLQFLAB0AAAEOASMiJy4DIyIGByM+ATMyHgYzMjY3Ai0JPC8law81GSANITA" +
    "IHAo6MBAnGTgYMBkjDiIvCQFLMEMlBRMIBzEiMUIIBxMIEQgIMCIAAAABACv/7wIfAr8AQAAAASMmIyIGFRQeARczFSMWFRQOAQc2MzIXHgMzMjY" +
    "3FwYjIi4DJyYjIgcnPgE1NCcjNTMuBDU0NjMyFgH9KAO9U2cSLAWfkRkhJCNALCQwBSQRHQwiTBsWRlYNGSEPKgMkIjY/GjJBHVBBAx0IEgZ+ZnR" +
    "zAdPIUkMdNEsLGDgyJ0gsIyESAg0FBiUeHkoDCgQQAQ0tJCRnNzQ8GAU0EikiE1JlegAAAAACADkAiAHzAkIAGgAkAAA/ASY0Nyc3FzYzMhc3Fwc" +
    "WFRQHFwcnBiMiJwcTIgYUFjMyNjQmOj8xMUAYPz1JTDpAFz8xMkAXQD1JSzpAxUdkZUZIZGSgPz6QPkAXQDExQBg/QUVGQEAXQDIyPwGHZI5kZI5" +
    "kAAIAXP+nAIIClQADAAcAABc1MxUDNTMVXCYmJln6+gH0+voAAAIAMv9QAfgCxgA1AEgAAAEjJiMiBhUUHgIXFhcWFRQGBxYVFAYjIiY1Mx4BMzI" +
    "2NTQnLgInLgI1NDY3JjU0NjMyFgUGFRQeAhceAhc2NTQnJicmAb8oBoY1QxEsEx+GKUc9NTxfTFZgKAJIRDlIKRM4ZwopLSs6NDVbRlVc/v1hEiQ" +
    "bFxBKNxhmPTdxIwIWjTgsFyUjDBFKIjpDLkwSMz0/T2JXSkw7LjIhDyU8BhkiQiYwShMsPTtNW6opThYmIBQOCisiESBROC4rPhMAAAADACL//QL" +
    "+AtkACwAXADEAAAEyFhUUBiMiJjU0NhciBhUUFjMyNjU0JhMOASMiJjU0NjMyFhcjLgEjIgYVFBYzMjY3AZCY1teXmNbXl43GyIuNx8gjCV48WG1" +
    "pVEBiBiAJSjNIU1hJMEkLAtnXl5jW2JaY1hvHjI3Gx4yNxv5dOkh+WFd9Tz0zPGxJTW43LgACAEIAdwE3AaQABgANAAABFQcXFSc1JxUHFxUnNQE" +
    "3WFh1DVZWcwGkMGlkMIAnhC9oYzGAKQAAAAEANwCgAiABeAAFAAATNSEVIzU3AekiAVch2LcAAAAABAAQAWoBfgLZAAsAFgAqADMAABMyFhUUBiM" +
    "iJjU0NhciBhUUFjMyNjQmBzMyFhUUBxYVFBcjJjU0JisBFSM3MzI1NC4BKwHHTGtsS0xrbEtDX2BCQ19ghk4eKiMhBhkFGiYlFxctOxgRFCsC2Wx" +
    "LTGxtS0xrFWBCQ2Bghl9AHRwhDRAuEwoKDSMXUWYlERABAAAAAAIAOwGhAVYCvAAKABQAABMyFhUUBiImNTQ2FiIGFBYzMjY1NMg7U1R0U1NnWj9" +
    "ALC1AArxTOzpTUzo7UyFAWj9ALC0AAgA0//wCHQHmAAsADwAAJTUjNTM1MxUzFSMVBTUhFQEX4+Mj4+P++gHpTLwhvb0hvFAhIQAAAAABADv/RwH" +
    "NAgAAFQAAATMRIzUGIyInFSMRMxEUFjMyNz4BNQGlKCc+cmMvKSlIS00yHRICAP4AanpU/QK5/rtMWzsjSjYAAAABADv/WgIWAsgADwAAASMRIxE" +
    "jESMRIiY1NDY7AQIWOCWIJF9ziG/kAqn8sQNP/LEBs3tecHIAAAEAagD9AJwBYwADAAATFSM1nDIBY2ZmAAIATwB3AUMBogAGAA0AABMXFQc1Ny8" +
    "BFxUHNTcn0HNzV1eBdHRYWAGigSeDMGdiMoAnhC5pZQAAAwAwAEcCKQHUAAMABwALAAABIzUzFyE1IQcjNTMBRjIy4/4HAfnjMjIBcGTXIddkAAA" +
    "AAAEACf9JAecCuwArAAABByMDDgQjIic3FjMyPgc3EyM3Mzc+AzMyFwcmIyIGDwEBnwd4SQcLGB4zIRgaBhcUDxoVDw0JCAQHAUVuB20TCBEiOCk" +
    "eHgcmDjcxCxMBrCH+giMrPCEZBiQEBxAPHBIkECcFAWghYio1NRkFJAVHPmYAAwA6AAACHgN3AAsADwATAAABFSERIRUhESEVIRElFSM1IxUjNQI" +
    "a/ksBmv5mAbn+HAFVK4QqAsgm/uMm/sgnAsivZ2dnZwAAAf/8/4UCngLIABwAACUVIxEjNSEVIRE2MzIeAhUUBgc1PgE1NCYjIgYBBCvdAiH+5zK" +
    "NOVcyGYxqW3ReX1RikJACoiYm/niIKkVQK3GyECYTm19Qd38AAAIAQwAAAfgDjQADAAkAAAEHIzcXIREjESEBc4Qkdbj+disBtQONjIzr/V4CyAA" +
    "AAAEAH//wApkC2QAcAAABDgEjIiY1NDYzMhYXIy4BIyIGByEVIR4BMzI2NwKZCqqAk7O3lGysDCoTiGF4mwoBd/6IAZx/cYwNARSCosunqM9/aFl" +
    "npIcmlbaOcAAAAQAo//ECTQLXADUAAAEjJiMiBhUUHgMXFhceBhUUBiMiJjUzHgEzMjY1NC4GJyYnJjU0NjMyFgI7KwvVXmoWJDo9KRYLIh09His" +
    "VEI59g5cpAn9yaXYOEyUcMxo3CW8kZINzdYwB/bRPRh8uHhcPCQQDCAcTEB4hMR1fbH59bGtXThcmHBgODwYMAhoQLWhXZWwAAAEAQAAAAGsCyAA" +
    "DAAATESMRaysCyP04AsgAAAAD/+kAAADCA3cAAwAHAAsAABMRIxE3FSM1IxUjNWkrhCuEKgLI/TgCyK9nZ2dnAAABABf/8AGjAsgAEQAAAREUIyI" +
    "mNTQ3MxUUFjMyNjURAaPFal0BKUNaVkQCyP350WxqDg0VXFtaVQIEAAACAA//9wPVAsgAHgApAAABETMyFhUUDgIrAREhAw4DIyInNRYzMj4CNxM" +
    "BIxEzMj4CNTQmAjXBa3QoREAj/P7mDwENHTgnMBgXMRonFAoBDwI3yM4yRyENVALI/sJlXjxUJxACo/4/K0pKLAkoDCdBPiAB5v6e/r8iNzAYQV8" +
    "AAAIAPwAAA9UCyAAUAB8AACkBESERIxEzESERMxEzMhYVFA4CAyMRMzI+AjU0JgMG/u/+dSsrAYsr1mt0KERALN3jMkchDVQBZv6aAsj+wgE+/sJ" +
    "lXjxUJxABZv6/IjcwGEFfAAAB//QAAAKLAsgAHQAAJRUjNTQmIyIOBAcRIxEjNSEVIRE2MzIeAwKLK0VpEyogJhQdAivdAiH+52pMOE8wGgiUlJR" +
    "/cgcKEAoPAf62AqImJv7RNxkqSk8AAgA9AAACdwONAAsADwAACQIjAQcVIxEzEQEnByM3AmP+uAFcN/68lCsrAcKZhCR1Asj+2P5gAYOH/ALI/mc" +
    "BmcWMjAAC//T/9AI7A3EAEgAfAAAlATMbATMBDgEjIiYnNRYzMjY3Ew4BIyImJzMWMzI2NwEK/uow++4u/tcTQSMSLwocKhsyC7UGTDE4TAchFVQ" +
    "lOAaUAjT9+gIG/YQpLw0JLRwiGQMbMUdAOFcxJgABAD//RwJdAsgACwAAIRUjNSMRMxEhETMRAWQr+isByCu5uQLI/V4Cov04AAL/8wAAAl0CyAA" +
    "HABEAAAkBIychByMBEwMuAScOAgcDAUIBGzBZ/qlbLwEhsoIFEQQDCwkEhQLI/Tjm5gLI/kIBSgw0CwgdGAv+swACAD8AAAJVAsgADgAXAAATIRU" +
    "hESEyFhUUDgIjIQEhETMyNjU0Jj8B6P5DAQhreDBMSCP+0QE6/vH3aWBYAsgm/upoXTlTKRIBZv7AXUNAYAAAAAADAD4AAAJVAsgADwAXAB4AABM" +
    "hMhYVFAYHHgEVFAcGIyETETMyNTQmIwMRMzI1NCM+ASVcfks+SFlTPXT+7SvgyWlS7uXc1gLIWlc+WQsIXklnNygCo/7gj0xF/rz+x6GYAAAAAQB" +
    "DAAAB+ALIAAUAAAEhESMRIQH4/nYrAbUCov1eAsgAAAAAAgAK/0cCjgLIAAwAEQAABTUhFSM1MzYRIREzFQMhAgchAmP90is/agGKUXz+zAleAZu" +
    "5ubnfxAHe/V7fA1z+NrMAAAABADoAAAIeAsgACwAAARUhESEVIREhFSERAhr+SwGa/mYBuf4cAsgm/uMm/scmAsgAAAAAAf/wAAAD5ALIABMAACE" +
    "BBxEjEScBIwkBMwERMxEBMwkBA67+0YArgP7RNQFF/s83AZkrAZk4/s8BRQGVdf7gASB1/msBsgEW/ooBdv6KAXb+6v5OAAAAAAEAKP/xAk0C2QA" +
    "nAAAlFAYjIiY1Mx4BMzI2NTQHIgc1MzI2NTQmIyIHIz4BMzIWFRQGBxUWAk2ebYOXKQJ/cliI0z8LSlFxcVjWCysHkHVth1U8oMZhdH59bGtkTZw" +
    "CASZMT0hLtG5sXVxJXAYCEgABAEAAAAJfAsgACwAAIREjASMRMxEzATMRAjQD/kQ1KwMBuzYCkf1vAsj9bwKR/TgAAAAAAgBAAAACXwNxAAwAGAA" +
    "AAQ4BIyImJzMWMzI2NxMRIwEjETMRMwEzEQHfBkwxOEwHIRVUJTgGdgP+RDUrAwG7NgNxMUdAOFcxJvyPApH9bwLI/W8Ckf04AAEAPQAAAncCyAA" +
    "LAAAJAiMBBxUjETMRAQJj/rgBXDf+vJQrKwHCAsj+2P5gAYOH/ALI/mcBmQAAAQAT//cCXwLIABUAACERIQMOAyMiJzUWMzI+AjcTIRECNP7ADwE" +
    "NHTgnMBgXMRonFAoBDwGVAqL+QCtKSiwJKAwnQT4gAeb9OAAAAAEAPwAAAuoCyAAZAAABESMRNDcOAQcDIwMmJxYVESMRMxMXNjcSNwLqKgYGFAb" +
    "7KvwCHwUqPOM4EiCkQwLI/TgCFUVGDjgO/bQCRQRVcxb96wLI/fCLM0oBgZ0AAQBAAAACXwLIAAsAAAERIxEhESMRMxEhEQJfK/43KysByQLI/Tg" +
    "BYf6fAsj+vwFBAAAAAAIAIP/vAsUC2QAKABcAAAEyFhUUBiAmNTQ2FyIOARUUFjMyNjU0JgFxl728/tC5u5ZbiEKig4SkpQLZ0qily82ops8mX5V" +
    "Zl7q4lJa8AAAAAQBAAAACXwLIAAcAAAERIxEhESMRAl8r/jcrAsj9OAKi/V4CyAAAAAIAQgAAAj8CyAAMABkAABMhMhcWFRQHBisBESMTETMyNzY" +
    "1NCcuAiNCARVnMVBKOFr2KyvdVilLPxQwISACyCE2bmk2Kf7FAqL+vhgsXVwpDQ0CAAEAJ//wAqEC2QAYAAABDgEjIiY1NDYzMhYXIy4BIyIGEBY" +
    "zMjY3AqEKqoCTs7eUbKwMKhOIYYCenIBxjA0BFIKiy6eoz39oWWe5/tS3jnAAAf/xAAACFQLIAAcAAAEVIxEjESM1AhX8K/0CyCb9XgKiJgAAAf/" +
    "0//QCOwLIABIAACUBMxsBMwEOASMiJic1FjMyNjcBCv7qMPvuLv7XE0EjEi8KHCobMguUAjT9+gIG/YQpLw0JLRwiGQAAAwAdAAACtQLIABEAGQA" +
    "hAAAlFSM1IiY1NDYzNTMVMhYVFAYDIxE+ATU0JisBIgYVFBYXAX4qg7S0gyqDtLR6CXmSmJ0JapiSeVJSUpCEgpVLS5WChJACBf4fCHR0b4KCb3R" +
    "0CAAAAAAB/+8AAAI7AsgACwAAAQMBIwsBIwEDMxsBAi7+AQs18fMzAQz9NOPoAsj+pv6SAU3+swFuAVr+xQE7AAABAD//RwKnAsgACwAABTUhETM" +
    "RIREzETMVAnz9wysByCtKubkCyP1eAqL9Xt8AAAABAD8AAAI1AsgAEwAAIREOASMiJj0BMxUUFjMyNjcRMxECCx2YNHppK0xoQ4giKgFgDCVkhq+" +
    "ibmQiDwFD/TgAAQA/AAADsALIAAsAADMRMxEhETMRIREzET8rAXgrAXkqAsj9XgKi/V4Cov04AAAAAQA//0cD+gLIAA8AAAU1IREzESERMxEhETM" +
    "RMxUDz/xwKwF4KwF4K0q5uQLI/V4Cov1eAqL9Xt8AAAAAAv/7AAAC8gLIAA4AGQAAJRQOAiMhESM1IREzMhYHNCYrAREhMj4CAvIoREAj/tH5AST" +
    "0anUrVFn7AQEyRyENxzxUJxACoib+xGdfQV/+wCI2MAAAAwA/AAAC6QLIAAMAEAAbAAAhETMRKQERMxEzMhYVFA4CAyMRITI+AjU0JgK+K/6F/tE" +
    "r9Gp1KERALPsBATJHIQ1UAsj9OALI/sRnXjxUJxABZv7AIjYwGEFfAAACAD8AAAI9AsgADAAXAAApAREzETMyFhUUDgIDIxEhMj4CNTQmAW7+0Sv" +
    "0anUoREAs+wEBMkchDVQCyP7EZ148VCcQAWb+wCI2MBhBXwAAAAEAH//wApkC2QAcAAABFAYjIiYnMx4BMzI2NyE1IS4BIyIGByM+ATMyFgKZs5O" +
    "AqgopDYxxf5wB/ogBdwqbeGGIEyoMrGyUtwFip8uignCOtpUmh6RnWWh/zwAAAgBA/+8DtALZABIAHwAAATIWFRQGIyImJyMRIxEzETM+ARciDgE" +
    "VFBYzMjY1NCYCYJe9vJiXuQGkKyulC7eOW4hCooOEpKUC2dKopcvMpv6fAsj+v5i6Jl+VWZe6uJSWvAAAAAL/7QAAAjoCyAANABYAACERIQMjEy4" +
    "BNTQ2MyERAyMiBhUUFjsBAg/+/ewz8kxjemcBKSv+TmhwXecBR/65AU0MYlBYZf04AqNLSlJQAAAAAgAe//IB8wIOACoAOAAAJRUGIyImPQEOASM" +
    "iJjU0Nz4BNzY1NCYjIgcjPgEzMhceAhURFB4CMzIDBgcOAQcGFRQWMzI2NQHzERgiGSFeSVBZxGcyCgdKR48MJgVmWmcxDg4BAQcQDQpWDxQfnig" +
    "8SD1SbSQgBiUxGUA7TEONEAgLEAsqOjyJU1g3EC0cHv73Dw4SCAECDQYKEBIbQzQ8Zk0AAAACACr/7wH4AtkAIwAtAAAlFAYjIiYnJjU0PgM/AT4" +
    "CNzMOAQ8BDgMHMz4BMzIWBzQmIgYVFBYyNgH4fGtRahYWCBwsTjRiGhgbAiYFODtZLkYpFgIDHGlGY3omZ7RnZ7Rn93CYUkA/YTFcbFE7BgsDBA4" +
    "NHyAHCgU2UlUtPEeXb2CFhWBhhoYAAwA1AAABzwIAAA8AGgAiAAAhIxEzMhYVFAYHFR4BFRQGAyMVMzI+AjU0JgcjFTMyNjU0ARDb20xmOzI4Qm1" +
    "Yq5YbMzYhVk+Wq0VXAgA8Qi09BwEFQzJJTQHdvQgUKR0uLeDaPTZnAAABADwAAAGQAgAABQAAExEjESEVZCgBVAHd/iMCACMAAAIAB/9fAg0CAAA" +
    "OABUAAAU1IRUjNTM+AT0BIREzFQMjFRQGByEB5f5KKDwkJAE8Rm7sJSEBMqGhocRK8Hcs/iPEAn4naehCAAIAIf/vAeoCDgATABkAACUOASMiJjQ" +
    "2MzIWHQEhFBYzMjY/ATQmIgYHAeUOdFlqf4FobHT+YWFfRl0PBF+wXgmuVmmS9JmYcA5hhlJLbVV6dFsAAAH/9QAAAt0CAAATAAATAyMTJzMBETM" +
    "RATMHEyMDBxUjNfvSNOrSNwERKAERN9LqNNJaKAEO/vIBK9X+5gEa/uYBGtX+1QEOXLKyAAABAB3/8QG1Ag4AJwAAARQGBxUeARUUBiMiJjUzFDM" +
    "yNjU0JisBNTMyNjU0JiMiByM+ATMyFgGoPDA3QnVSYXAoqT5gWE0uJERgUTyWCykBcFpOZQGILkEGAQVJNEpVY1mYRTY3NiMxNzAzgE9UQwAAAQA" +
    "4AAABzwIAAAsAACERIwEjETMRMwEzEQGnAf7DMSgBATwyAcz+NAIA/jIBzv4AAAAAAAIAOAAAAc8CyAAMABgAAAEOASMiJiczFjMyNjcTESMBIxE" +
    "zETMBMxEBigZMMThNByEWVCU4Bj4B/sMxKAEBPDICyDFHQTdXMSb9OAHM/jQCAP4yAc7+AAABADkAAAHeAgAACwAAISMDBxUjETMRATMHAd4z2nA" +
    "oKAE3N+EBFGmrAgD+2gEm0gABABH/9gHiAgAADwAAIREjAwYjIic1FjMyNxMhEQG67woHcB8aGCBLBwsBPAHd/u7VCiQLtgEx/gAAAAABADgAAAI" +
    "/AgAADgAAExEjETMbATMRIxEjAyMDYChAxMNAKALEKsUB3P4kAgD+LwHR/gAB3P4kAdwAAAABADgAAAHPAgAACwAAIREhFSMRMxUhNTMRAaf+uSg" +
    "oAUcoAP//AgDf3/4AAAIAH//xAfoCDwALABcAAAEyFhUUBiMiJjU0NhciBhUUFjMyNjU0JgEOa4GBbG2Bg2tYbWtbWGpqAg+VfXuRk3x6lSOCamy" +
    "Af2ptggABADgAAAHPAgAABwAAASERIxEhESMBp/65KAGXKAHf/iECAP4AAAAAAgA+/0cCCAIOAA8AHAAAExU2MzIWFRQGIyImJxEjERciBhUUHgE" +
    "zMjY1NCZkMo1ofX1nR2QTKONZZCVZQFVnZgIAeoiVfHqVRkD+0wK5FH9xP2dGgmtugQAAAAABACT/8QHpAg8AGQAAJQ4BIyImNTQ2MzIWFyMuASM" +
    "iBhUUFjMyNjcB6QxzW3B7g21ZbgopCFpFW21qV0pfCrRcZ5l0fZRbUT9LgWxrglZLAAEACAAAAbQCAAAHAAATESMRIzUhFfIowgGsAd3+IwHdIyM" +
    "AAAH/9/9IAb8CAAAYAAABAw4DIyInNRYzMjY3NjcDMxMWFzY3EwG/3Q8PIC0hFRIQESQqDxgL2S2pCA8TBZgCAP3LJyAsEAIkAx8kNxwB//5vEy0" +
    "4DQGMAAADACT/RwLaAsgAGwAoADUAAAEUBiMiJxUjNQYjIiY1NDYzMhYXETMRPgEzMhYHNCYjIgYdARQWMzI2BTU0JiMiBhUUFjMyNgLaZ15SMCg" +
    "wUl5nZF4pRxUoFUcpXmQqTlQuTU4uTlP+u00uVE5TTi5OAQFzmkv4+Euac3SZLSEBCP74IS2ZdGaFUDXPNE2HBs81UIVmY4dNAAH/+QAAAcQCAAA" +
    "LAAABBxMjJwcjEyczFzcBsLnNNLO0MMu7NKCjAgDy/vLw8AEM9NbWAAABADf/XwIPAgAACwAABTUhETMRIREzETMVAef+UCgBRyhBoaECAP4jAd3" +
    "+I8QAAAABADYAAAGwAgAAEwAAITUOASMiJj0BMxUUFjMyNjc1MxEBiBtrKFZOKD8+KGobKPkLHE5aho1GNx0M4f4AAAAAAQA3AAACxQIAAAsAADM" +
    "RMxEhETMRIREzETcoAQsoAQsoAgD+IwHd/iMB3f4AAAAAAQA2/18DBgIAAA8AAAU1IREzESERMxEhETMRMxUC3v1YKAEMKAELKEGhoQIA/iMB3f4" +
    "jAd3+I8QAAAAAAv//AAACRwIAAAsAFAAAJRQGKwERIzUzFTMyBzQmKwEVMzI2AkdgUOay263AKlxEo7dBS6BNUwHdI8yUPDXuRAAAAAADADYAAAI" +
    "/AgAAAwANABYAACERMxEhIxEzFTMyFRQGAyMVMzI2NTQmAhco/srTKZnBYGuPpEFLXAIA/gACAMyUTVMBEe5EOTw1AAAAAgA2AAABzQIAAAkAEgA" +
    "AISMRMxUzMhUUBgMjFTMyNjU0JgEd5ymtwWBro7hBS1wCAMyUTVMBEe5EOTw1AAAAAAEAH//xAeMCDwAcAAAlFAYjIiYnMx4BMzI2NyE1IS4BIyI" +
    "GByM+ATMyFgHje3BZcg4oDF9HVmkC/u0BEghqVUNYCykMblZtg/50mWJYR1F/aiJfcEY8TVeUAAAAAgA4//ECugIPABIAHgAAATIWFRQGIyImJyM" +
    "VIxEzFTM+ARciBhUUFjMyNjU0JgHOa4GBbG2AAX8oKIAJgWNYbWtbWGpqAg+VfXuRknz/AgDfbYEjgmpsgH9qbYIAAAAAAv/7AAABuQIAAA8AGAA" +
    "AITUjIicHIzcuATU0NjsBEQMjIgYVFBY7AQGRlxcLqTSuPj1lU9MopUVQVkOh2AHZ3w1SMktF/gAB3Tc2PTgAAAAEACH/7wHqAsoAEwAZAB0AIQA" +
    "AJQ4BIyImNDYzMhYdASEUFjMyNj8BNCYiBgcBFSM1IxUjNQHlDnRZan+BaGx0/mFhX0ZdDwRfsF4JASUrhCquVmmS9JmYcA5hhlJLbVV6dFsBr2d" +
    "nZ2cAAAABAAD/SAHbAsgAJQAAJRQGBzU+AT0BNCMiBh0BIxEjNTM1MxUhFSEVMz4BMzIeBBUB24ptXHOSVWUoPz8nAQf++QITaT4rQicZCQNsbKs" +
    "NIQ+NWFyod2CKAd0jyMgj1ThCFScnNyAWAAIAOQAAAY0C4AADAAkAAAEHIzcDESMRIRUBNIQkdaAoAVQC4IyM/v3+IwIAIwAAAAEAJf/xAekCDwA" +
    "cAAAlDgEjIiY1NDYzMhYXIy4BIyIGByEVIR4BMzI2NwHpDnJZcHuDbVZuDCkLWENVaggBEv7tAmlWR18Mq1himXR9lFdNPEZwXyJqf1FHAAAAAQA" +
    "h//ABvAIOADwAAAEjLgEjIgYVFB4IFx4EFRQGIyImNTMUFjMyNjU0LgMnJicuCDU0NjMyFgGtKQZPSUBLBQcQChkMIA0lBiUgQB8ab1thcChZUkd" +
    "ZFRgxGRsJBAcpFCYUHhARB2NYWWcBa0Q8Ni4MFA8PCQsFCAQIAQgJGRswH0RTY1lMTD4zFiMVEwYGAgECCQQLCg8TGB4SQUpTAAIAQAAAAGgCyAA" +
    "DAAcAABMVIzUXESMRaCgoKALIZWXI/gACAAAAAAAD/+gAAADBAsoAAwAHAAsAABMVIzUjFSM1FxEjEcErhCqAKQLKZ2dnZ8r+AAIAAAAC/9z/RQB" +
    "pAsgADAAQAAATERQGIyInNTMyNjURNxUjNWkwRQQUFDEgKCgCAP3KSD0CIik1AjnIZGQAAAACABH/9gLtAgAAFQAdAAAlFAYrAREjAwYjIic1FjM" +
    "yNxMhFTMyBzQrARUzMjYC7WBQr8MKB3AfGhggSwcLARB2wSqhbIFCSp1MUQHd/u7VCiQLtgEx0pFu6EEAAAIANwAAAu0CAAARABkAACEjESERIxE" +
    "zFSE1MxUzMhUUBgMjFTMyNjU0Aj3E/uYoKAEaKIvBYGuBlkJKAQv+9QIA0tLSkUxRAQvoQTluAAAAAQAAAAAB2ALIABkAACEjNTQjIgYdASMRIzU" +
    "zNTMVIRUhFTM2MzIVAdgoj1VlKD8/JwEH/vkCM4qzuah1YooB3SPIyCPVetAAAgA5AAAB3gLgAAMADwAAAQcjNxMjAwcVIxEzEQEzBwFShCR1vzP" +
    "acCgoATc34QLgjIz9IAEUaasCAP7aASbSAAL/9/9IAb8CyAAMACUAAAEOASMiJiczFjMyNjcXAw4DIyInNRYzMjY3NjcDMxMWFzY3EwFmBkwxOE0" +
    "HIRZUJTgGet0PDyAtIRUSEBEkKg8YC9ktqQgPEwWYAsgxR0E3VzEmyP3LJyAsEAIkAx8kNxwB//5vEy04DQGMAAABADj/XwHPAgAACwAAIRUjNSM" +
    "RMxEhETMRARgouCgBRyihoQIA/iIB3v4AAAEAPwAAAfQDcgAHAAATESMRITUzFWorAYorAqL9XgLIqtAAAAEAOQAAAY0CoQAHAAABFSERIxEhNQG" +
    "N/tQoASwCocT+IwIAoQAAAAABAAAA/QH0ASMAAwAAARUhNQH0/gwBIyYmAAAAAQAAAP0D6AEjAAMAAAEVITUD6PwYASMmJgAAAAEATQHwAI0C1gA" +
    "JAAATBgczFSM1NDY3jSEBFDIZJwK0FUlmVTZKEQABAD8B4gB/AsgACQAAExUUBgc1NjcjNX8ZJyEBFALIVTZKESIVSWYAAQA9/4AAfQBmAAkAADc" +
    "VFAYHNTY3IzV9GSchARRmVTZKESIVSWYAAAIARgHwAQMC1gAJABMAAAEGBzMVIzU0NjcHBgczFSM1NDY3AQMhARQyGSd9IQEUMhknArQVSWZVNko" +
    "RIhVJZlU2ShEAAgA2AeIA8wLIAAkAEwAAExUUBgc1NjcjNTMVFAYHNTY3IzV2GSchARSvGSchARQCyFU2ShEiFUlmVTZKESIVSWYAAAACADb/gAD" +
    "zAGYACQATAAA3FRQGBzU2NyM1MxUUBgc1NjcjNXYZJyEBFK8ZJyEBFGZVNkoRIhVJZlU2ShEiFUlmAAAAAAEANf9vAfcCyAALAAABFSMRIxEjNTM" +
    "1MxUB984nzc0nAd8j/bMCTSPp6QAAAQA1/28B9gLIABMAAAEVIxEzFSMVIzUjNTMRIzUzNTMVAfbNzc0mzs7OziYCAyT+eSTFxSQBhyTFxQAAAQB" +
    "IALIBrAIWAAsAABMyFhUUBiMiJjU0NvpKaGlJSmhpAhZpSUpoaUlKaAADAI0AAANZAGYAAwAHAAsAADcVIzUhFSM1IRUjNb8yAX8yAX8yZmZmZmZ" +
    "mZgAAAAAHACz/4QQLAtUAAwAOABoAJQAwADoARQAACQEnAQMyFhUUBiMiJjQ2ITIWFRQGIyImNTQ2ADIWFRQGIyImNTQBIhUUFjMyNjU0JiUiBhQ" +
    "WMjY1NCYBIgYVFBYyNjU0JgJi/isjAdUxRlJPR0lPTwGtR1BRRkhQUP1QjlFTRkdPAeJyOzg3PD0BLzc+PW48PP0YNj08bj09AtX9DAEC8/5yWE1" +
    "SWlegWlhOT1xYT1BaAXtZT05cWVFP/sCOQkZKREBIAUqESUpEQUgBektDQUdKQUJJAAEAQAB3ALMBowAGAAATFQcXFSc1s1dXcwGjMmZjMYEoAAA" +
    "AAAEAUQB3AMQBowAGAAATFxUHNTcnUXNzWFgBo4EogzFnYwAAAAQAQQAAA44CrQALABMAGwAfAAAzETMBMxEzESMBIxEkIiY0NjIWFAYyNjQmIgY" +
    "UFyE1IUE1AZsCKjL+YgIC1YBISIBIt14xMV4x7v7uARICrf2OAnL9UwJ3/Yl+UYBRUYAsPlw+PlzhKwAAAAIAagFkAyECyAAHABQAABMRIzUhFSM" +
    "RMxEzGwEzESMRAyMDEeuBASCByC57eywbfxt/AWQBSBwc/rgBZP7FATv+nAFD/r0BQ/69AAACAA4AAAJyAsgAAwAGAAAJASEBAyEDAU8BI/2cAR/" +
    "sAfv/Asj9OALI/VsCeAAAAAABABj/KgH6AxEACAAAAQMjAwcnNxsBAfrXILIsDUmtywMR/BkBbhUbJP6ZA7YAAAADAC8AiwKjAZIALgA/AFEAAAE" +
    "+BzMyFhUUBiMiLgYnDgQjIiY1NDYzMh4IFx4EMzI2NTQmIyIOAgcuBiMiBhUUFjMyPgEBaQQfDB4RHhYdDThGRTkOHRYdER4LIAQJLxkqKhc5RUU" +
    "2CxcSGQ4bChsGHRcHKhcnJBMrMjEqFSw3E0oCIwwhEx4aDScxMSwdQyYBIwMdChoLEgcHSjg6SwYIEQoZCh0ECCoTGwxJOTdNBAUNBxMHGAUaFwY" +
    "lEhkLNi0qOBEqDxoCHwkaCw8GOigsNiQfAAIAKgCLAi0BkgAdADsAAAEOASMiJy4DIyIGByM+ATMyHgYzMjY3Fw4BIyInLgMjIgYHIz4BMzIeBjM" +
    "yNjcCLQk8LyVrDzUZIA0hMAgcCjowECcZOBgwGSMOIi8JGwk8LyVrDzUZIA0hMAgcCjowECcZOBgwGSMOIi8JAZIwQyUFEwgHMSIxQggHEwgRCAg" +
    "wIo0wQyUFEwgHMSIxQggHEwgRCAgwIgAAAAEANAAUAh0CCAATAAA/ASE1ITcXBzMVIwchFSEHJzcjNexQ/vgBGkwdRKq8UQEN/uJLHUOmwpYhjw+" +
    "AIZYhjQ9+IQAAAgA0//ICHQHwAAYACgAAEzUlFQ0BFQUhFSE0Aen+QwG9/hcB6f4XAQQkyCW1tCUqIQAAAAIANP/yAh0B8AAGAAoAAAEFNS0BNQU" +
    "RFSE1Ah3+FwG+/kIB6f4XAQTHJbS1Jcj+6yEhAAABAEUA+wEbASIAAwAAARUjNQEb1gEiJycAAAAAAAAWAQ4AAQAAAAAAAADxAeQAAQAAAAAAAQA" +
    "QAvgAAQAAAAAAAgAEAxMAAQAAAAAAAwBBA5wAAQAAAAAABAAVBAoAAQAAAAAABQAHBDAAAQAAAAAABgAVBGQAAQAAAAAABwBRBR4AAQAAAAAACAA" +
    "/BfAAAQAAAAAAEAAQBlIAAQAAAAAAEQAEBm0AAwABBAkAAAHiAAAAAwABBAkAAQAgAtYAAwABBAkAAgAIAwkAAwABBAkAAwCCAxgAAwABBAkABAA" +
    "qA94AAwABBAkABQAOBCAAAwABBAkABgAqBDgAAwABBAkABwCiBHoAAwABBAkACAB+BXAAAwABBAkAEAAgBjAAAwABBAkAEQAIBmMAQwBvAHAAeQB" +
    "yAGkAZwBoAHQAZQBkACAAKABjACkAIAAxADkAOAAxACwAIAAxADkAOQA3ACAAYgB5ACAAYQBuAGQAIAB0AGgAZQAgAHAAcgBvAHAAZQByAHQAeQA" +
    "gAG8AZgAgAEwAaQBuAG8AdAB5AHAAZQAtAEgAZQBsAGwAIABBAEcAIABhAG4AZAAvAG8AcgAgAGkAdABzACAAcwB1AGIAcwBpAGQAaQBhAHIAaQB" +
    "lAHMALgAgAEEAbABsACAAUgBpAGcAaAB0AHMAIABSAGUAcwBlAHIAdgBlAGQALgAgAEEAbABsACAAQwB5AHIAaQBsAGwAaQBjACAAYwBoAGEAcgB" +
    "hAGMAdABlAHIAcwAgAGQAZQBzAGkAZwBuAGUAZAAgAGIAeQAgAEQAbwB1AGIAbABlAEEAbABlAHgALgAgAEgAZQBsAHYAZQB0AGkAYwBhACAAaQB" +
    "zACAAYQAgAHIAZQBnAGkAcwB0AGUAcgBlAGQAIABUAHIAYQBkAGUAbQBhAHIAawAgAG8AZgAgAEwAaQBuAG8AdAB5AHAAZQAtAEgAZQBsAGwAIAB" +
    "BAEcAIABhAG4AZAAvAG8AcgAgAGkAdABzACAAcwB1AGIAcwBpAGQAaQBhAHIAaQBlAHMALgAAQ29weXJpZ2h0ZWQgKGMpIDE5ODEsIDE5OTcgYnk" +
    "gYW5kIHRoZSBwcm9wZXJ0eSBvZiBMaW5vdHlwZS1IZWxsIEFHIGFuZC9vciBpdHMgc3Vic2lkaWFyaWVzLiBBbGwgUmlnaHRzIFJlc2VydmVkLiB" +
    "BbGwgQ3lyaWxsaWMgY2hhcmFjdGVycyBkZXNpZ25lZCBieSBEb3VibGVBbGV4LiBIZWx2ZXRpY2EgaXMgYSByZWdpc3RlcmVkIFRyYWRlbWFyayB" +
    "vZiBMaW5vdHlwZS1IZWxsIEFHIGFuZC9vciBpdHMgc3Vic2lkaWFyaWVzLgAASABlAGwAdgBlAHQAaQBjAGEATgBlAHUAZQBDAHkAcgAASGVsdmV" +
    "0aWNhTmV1ZUN5cgAAVABoAGkAbgAAVGhpbgAAVAByAGEAbgBzAFQAeQBwAGUAIAAzACAATQBBAEMAOwBIAGUAbAB2AGUAdABpAGMAYQBOAGUAdQB" +
    "lAEMAeQByAC0AVABoAGkAbgA7ADAAMAAxAC4AMAAwADAAOwA4AC8AMgA5AC8AMAA2ACAAMQAwADoAMwA5ADoANAA3ACAAQQBNAABUcmFuc1R5cGU" +
    "gMyBNQUM7SGVsdmV0aWNhTmV1ZUN5ci1UaGluOzAwMS4wMDA7OC8yOS8wNiAxMDozOTo0NyBBTQAASABlAGwAdgBlAHQAaQBjAGEATgBlAHUAZQB" +
    "DAHkAcgAtAFQAaABpAG4AAEhlbHZldGljYU5ldWVDeXItVGhpbgAAMAAwADEALgAwADAAMAAAMDAxLjAwMAAASABlAGwAdgBlAHQAaQBjAGEATgB" +
    "lAHUAZQBDAHkAcgAtAFQAaABpAG4AAEhlbHZldGljYU5ldWVDeXItVGhpbgAAUABsAGUAYQBzAGUAIAByAGUAZgBlAHIAIAB0AG8AIAB0AGgAZQA" +
    "gAEMAbwBwAHkAcgBpAGcAaAB0ACAAcwBlAGMAdABpAG8AbgAgAGYAbwByACAAdABoAGUAIABmAG8AbgB0ACAAdAByAGEAZABlAG0AYQByAGsAIAB" +
    "hAHQAdAByAGkAYgB1AHQAaQBvAG4AIABuAG8AdABpAGMAZQBzAC4AAFBsZWFzZSByZWZlciB0byB0aGUgQ29weXJpZ2h0IHNlY3Rpb24gZm9yIHR" +
    "oZSBmb250IHRyYWRlbWFyayBhdHRyaWJ1dGlvbiBub3RpY2VzLgAAYgB5ACAAYQBuAGQAIAB0AGgAZQAgAHAAcgBvAHAAZQByAHQAeQAgAG8AZgA" +
    "gAEwAaQBuAG8AdAB5AHAAZQAtAEgAZQBsAGwAIABBAEcAIABhAG4AZAAvAG8AcgAgAGkAdABzACAAcwB1AGIAcwBpAGQAaQBhAHIAaQBlAHMAAGJ" +
    "5IGFuZCB0aGUgcHJvcGVydHkgb2YgTGlub3R5cGUtSGVsbCBBRyBhbmQvb3IgaXRzIHN1YnNpZGlhcmllcwAASABlAGwAdgBlAHQAaQBjAGEATgB" +
    "lAHUAZQBDAHkAcgAASGVsdmV0aWNhTmV1ZUN5cgAAVABoAGkAbgAAVGhpbgAAAgAAAAAAAP+1ADIAAAAAAAAAAAAAAAAAAAAAAAAAAADqAAAAAQA" +
    "CAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwA" +
    "sAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQB" +
    "WAFcAWABZAFoAWwBcAF0AXgBfAGAAYQCFAL0A6ACGAIsAqQCkAIoAgwCTAJcAiADDAKoAuACmAQIBAwEEAQUBBgEHAQgBCQEKAQsBDAENAQ4BDwE" +
    "QAREBEgETARQBFQEWARcBGAEZARoBGwEcAR0BHgEfASABIQEiASMBJAElASYBJwEoASkBKgErASwBLQEuAS8BMAExATIBMwE0ATUBNgE3ATgBOQE" +
    "6ATsBPAE9AT4BPwFAAUEBQgFDAUQBRQFGAUcBSAFJAUoBSwFMAU0BTgFPAVABUQFSAVMBVAFVAVYBVwFYAVkBWgFbAVwBXQFeAV8AsgCzALYAtwD" +
    "EALQAtQDFAIIAwgCHAKsAxgC+AL8BYACMAKgApQCSAKcAjwCUAJUBYQFiCWFmaWkxMDAyMwlhZmlpMTAwNTEJYWZpaTEwMDUyCWFmaWkxMDA1Mwl" +
    "hZmlpMTAwNTQJYWZpaTEwMDU1CWFmaWkxMDA1NglhZmlpMTAwNTcJYWZpaTEwMDU4CWFmaWkxMDA1OQlhZmlpMTAwNjAJYWZpaTEwMDYxCWFmaWk" +
    "xMDA2MglhZmlpMTAxNDUJYWZpaTEwMDE3CWFmaWkxMDAxOAlhZmlpMTAwMTkJYWZpaTEwMDIwCWFmaWkxMDAyMQlhZmlpMTAwMjIJYWZpaTEwMDI" +
    "0CWFmaWkxMDAyNQlhZmlpMTAwMjYJYWZpaTEwMDI3CWFmaWkxMDAyOAlhZmlpMTAwMjkJYWZpaTEwMDMwCWFmaWkxMDAzMQlhZmlpMTAwMzIJYWZ" +
    "paTEwMDMzCWFmaWkxMDAzNAlhZmlpMTAwMzUJYWZpaTEwMDM2CWFmaWkxMDAzNwlhZmlpMTAwMzgJYWZpaTEwMDM5CWFmaWkxMDA0MAlhZmlpMTA" +
    "wNDEJYWZpaTEwMDQyCWFmaWkxMDA0MwlhZmlpMTAwNDQJYWZpaTEwMDQ1CWFmaWkxMDA0NglhZmlpMTAwNDcJYWZpaTEwMDQ4CWFmaWkxMDA0OQl" +
    "hZmlpMTAwNjUJYWZpaTEwMDY2CWFmaWkxMDA2NwlhZmlpMTAwNjgJYWZpaTEwMDY5CWFmaWkxMDA3MAlhZmlpMTAwNzIJYWZpaTEwMDczCWFmaWk" +
    "xMDA3NAlhZmlpMTAwNzUJYWZpaTEwMDc2CWFmaWkxMDA3NwlhZmlpMTAwNzgJYWZpaTEwMDc5CWFmaWkxMDA4MAlhZmlpMTAwODEJYWZpaTEwMDg" +
    "yCWFmaWkxMDA4MwlhZmlpMTAwODQJYWZpaTEwMDg1CWFmaWkxMDA4NglhZmlpMTAwODcJYWZpaTEwMDg4CWFmaWkxMDA4OQlhZmlpMTAwOTAJYWZ" +
    "paTEwMDkxCWFmaWkxMDA5MglhZmlpMTAwOTMJYWZpaTEwMDk0CWFmaWkxMDA5NQlhZmlpMTAwOTYJYWZpaTEwMDk3CWFmaWkxMDA3MQlhZmlpMTA" +
    "wOTkJYWZpaTEwMTAwCWFmaWkxMDEwMQlhZmlpMTAxMDIJYWZpaTEwMTAzCWFmaWkxMDEwNAlhZmlpMTAxMDUJYWZpaTEwMTA2CWFmaWkxMDEwNwl" +
    "hZmlpMTAxMDgJYWZpaTEwMTA5CWFmaWkxMDExMAlhZmlpMTAxOTMJYWZpaTEwMDUwCWFmaWkxMDA5OAlhZmlpNjEzNTILaHlwaGVubWludXMHbmJ" +
    "zcGFjZQAAAAH//wACAAEAAAAOAAAAMAAAAAAAAgAFAAMABwABAAgACAACAAkA2wABANwA3AACAN0A6QABAAQAAAACAAAAAQAAAAoAHgAsAAFsYXR" +
    "uAAgABAAAAAD//wABAAAAAWZyYWMACAAAAAEAAAADAAgAEgAaAAYAAAACABoASAAEAAAAAQBkAAQAAAABAHgAAwAAAAQAFgAcACIAKAAAAAEAAAA" +
    "BAAEAAQATAAEAAQASAAEAAQATAAEAAQATAAMAAAADABQAGgAgAAAAAQAAAAIAAQABABMAAQABABIAAQABABMAAQAWAAEACAABAAQA3AAEABIAEwA" +
    "TAAEAAQATAAEAFAABAAgAAQAEAAgAAwASABMAAQABABMAAQAAAAoAIAA6AAFsYXRuAAgABAAAAAD//wACAAAAAQACY3BzcAAOa2VybgAUAAAAAQA" +
    "AAAAAAQABAAIABgAOAAEAAAABABAAAgAAAAEAHAABAAoABQAHAA4AAgABACQAPQAAAAEGCgAEAAAAOwCAAIYAuADaAOgBAgEQAVIBgAGqAeAB5gI" +
    "AAgoCAAIUAhoCKAIoAhQCOgJYAmICaAJiAs4C4AL6AuADGAOSBDgEQgRMBGIC4AR4BIYEjAS2BIYEtgTIBNYE5AUOBSwFNgTIBMgFSAVOBU4FSAV" +
    "gBY4FoAXSBdwAAQCy/8QADACL/+4AkwAaAKH/ywCk/8IAp/+5AKr/1ACr/8IArP/UAK7/uQCx/7kAt//LAL//ywAIADf/zgA5/+EAOv/nADz/2wB" +
    "Z/+4AWv/uAFz/7gDT/8kAAwAP/4wAEf+MACT/2wAGADf/pAA5/6QAOv+2ADz/kQBc/8kA0/+xAAMAD/9wABH/cAAk/8kAEAAP/5EAEP+RABH/kQA" +
    "d/6kAHv+pACT/zgBE/6QARv+kAEj/pABM//IAUv+kAFX/pABW/6QAWP+kAFr/pABc/6QACwAP/6QAEP/bABH/igAd/9sAHv/bACT/1QBE/9sASP/" +
    "bAFL/2wBV/+4AWP/uAAoAD//JABD/2wAR/8kAHf/uAB7/7gAk//oARP/uAEj/7gBMABgAUv/uAA0AD/+MABD/ngAR/4wAHf/JAB7/yQAk/8kARP+" +
    "2AEj/tgBS/7YAU//JAFT/tgBY/9sAWf/uAAEA0wASAAYAD/+2ABD/yQAR/7YAWQASAFwAEgDTABIAAgAP/7YAEf+2AAIAD//JABH/yQABAJP/5gA" +
    "DABH/YQAd/40AHv+NAAQAkv++AJP/1ADT/7EA1v+xAAcAc//UAHz/1ACS/84Al//XALL/6ADT/8kA1v/JAAIAi//WAJf/1wABAIv/1gAZAA//YQA" +
    "Q/2EAEf9hABL/cwAd/40AHv+NAID/nQCE/8gAi/+fAKD/bACi/4QApP9QAKX/bACm/4QAqP+EAKv/UACs/4QArf+EAK7/bACw/4QAs/+EALb/hAC" +
    "9/2wAvv+EAL//bAAEAI7/7gCR/+4AlP/uAJ3/7gAGAHr/6ACE/+4Ahv/uAIv/1gCS/+4Alf/uAAcAD/9wABH/cAAS/9QAgP/JAIT/vgCL/64ApP/" +
    "XAB4AD/+RABD/kQAR/5EAEv+WAB3/qQAe/6kAgP/OAIv/zACO/+4Akf/uAJT/5gCd/+4AoP+kAKL/sgCl/6QAqP+yAKr/sgCr/4sArP+yAK3/sgC" +
    "u/6QAsP+yALP/pAC5/7IAu/+yALz/sgC9/6QAvv+yAL//pADA/88AKQAP/4oAEP/LABH/igAS/7EAHf/bAB7/2wB5/7EAev/XAID/xwCE/9cAi//" +
    "HAJH/7gCg/9sAof/bAKL/5gCj/+YApP/HAKX/2wCm/+YAp//bAKj/5gCp/+YAqv/mAKv/xwCs/+YArf/mAK7/2wCv/+YAsP/mALH/2wCy/+YAtP/" +
    "bALX/5gC2/+YAt//fALj/5gC5/+YAvf/bAL7/5gC//98AyP/HAAIAi//FAJL/5gACANP/sQDW/7EABQCS/74Ak//UAJf/vgDT/7EA1v+xAAUAhP/" +
    "uAIb/7gCL/9YAkv/uAJX/7gADAKT/7gCr/9YAsv/uAAEAq//gAAoAD/9vABD/nwAR/28AEv/CAKD/5gCk/9AApf/mAKv/qACu/+YAsf/mAAQApP/" +
    "gAKv/4ACy/+4AyP/gAAMApP/gAKv/1gCy/+4AAwCk/+AAq//gALL/7gAKAA//lgAQ/8IAEf+WAKD/7gCl/+4Aq//EAK7/7gCx/+4AtP/uAL3/7gA" +
    "HAA//tgAR/7YApP/uAKv/zQDI/9cA0wAjANYAIwACAKv/1gCy/+4ABACy/7cAt//cANP/wgDW/8IAAQCz/+YABACy/7cAs//uANP/wgDW/8IACwA" +
    "R/2EAHf+NAB7/jQCA/50AhP/IAIv/vgCg/2wApf9sAK7/bAC9/2wAv/9sAAQAoP/mAKX/5gCu/+YAsf/mAAwAev/CAID/wgCE/8sAhgAaAIv/wgC" +
    "SACMAkwAaAJUAGgCk/8IAq//CAMj/wgDS/7IAAgBW/8kA0/+yAAsAev/CAID/wgCE/8sAhgAaAIv/wgCSACMAkwAaAJUAGgCk/8IAq//CAMj/wgA" +
    "BADsAEAASACQAKQAvADMANwA5ADoAPABJAFUAWQBaAFwAcwB0AHoAewB8AIAAgQCCAIMAhwCKAI4AkACRAJIAkwCUAJoAnACdAJ4AoQCiAKMApQC" +
    "nAK4AsACxALIAswC0ALwAvQC+AMEAyADJAMoAzgDPANIA0wDVAAAAAQAAAADMPaLPAAAAAMEZyfMAAAAAwRnJ8w=="

const pdf = new jsPDF({
    unit: 'pt',
    orientation: 'p',
});

pdf.addFileToVFS("HelveticaThin.ttf", FontInBase64)
pdf.addFont("HelveticaThin.ttf", "HelveticaThin", "Bold")
pdf.setFont("HelveticaThin","Bold")

function downloadPdf(document, pdf ) {
    let fontSize = 12
    pdf.setFontSize(fontSize);
    // size plate
    const _minWidth = 30;
    const _maxWidth = 560;
    const _minHeight = 40;
    const _maxHeight = 800;
    // We form the fields for pdf
    // Name and contact inform
    let _name = document.getElementById('name').innerText
    let _contactDetails = document.getElementById('contactDetails').innerText
    // Photo
    let img = new Image();
    img.src = 'res/pic/headshot.jpg';
    // top info
    pdf.text(_name, 120, 60);
    pdf.text(_contactDetails, 440, 60)
    pdf.addImage(img, 'JPEG', _minWidth, _minHeight, 80, 80);
    pdf.setDrawColor(255, 0, 0);
    // Lines
    pdf.line(_minWidth, 130, _maxWidth, 130); // top line
    pdf.line(_minWidth, 215, _maxWidth, 215) // AboutMe end

    // main area
    const _startWidth_text = _maxWidth * .25 + 10
    const _endWidth_text = _maxWidth
    // AboutMe
    let _aboutMe_title = document.getElementById('aboutMe_title').innerText;
    let _aboutMe_text = document.getElementById('aboutMe_text').innerText;

    pdf.text(_aboutMe_title, _minWidth, 150)
    let splitTitle = pdf.splitTextToSize(_aboutMe_text, _endWidth_text - _startWidth_text);
    pdf.text(splitTitle, _startWidth_text, 150);

    // Hard Skills
    let _hardSkills_title = document.getElementById('hardSkills_title').innerText;
    let _hardSkills_text = [];
    let elements = document.getElementById('hardSkills_text').innerText;
    let element = elements.split("\n");
    element.forEach(element => {
        element.replace(/\s+/g, ' ').trim();
        _hardSkills_text.push(element)
    })
    let widthTextArea = _endWidth_text - _startWidth_text
    let arrXPos = [_startWidth_text,
        _startWidth_text+widthTextArea*.38,
        _startWidth_text+widthTextArea*.69]

    const yParallax = fontSize + 2
    let countRow = 0
    let maxCountRow = Math.ceil(_hardSkills_text.length/arrXPos.length)
    let itemsCount = 0
    let yPos = 235
    pdf.text(_hardSkills_title,  _minWidth, yPos)
    //
    for (yPos; countRow <= maxCountRow; yPos += yParallax){
        if (itemsCount>_hardSkills_text.length) break;
        arrXPos.forEach(element => {
            if (_hardSkills_text[itemsCount]!== undefined){
                pdf.text(_hardSkills_text[itemsCount], element,yPos)
            }
            itemsCount++
        })
        countRow++;
    }
    pdf.line(_minWidth, yPos, _maxWidth, yPos) // line hardSkills end
    yPos += 20
    // soft Skills
    let _softSkills_title = document.getElementById('softSkills_title').innerText;
    pdf.text(_softSkills_title, _minWidth, yPos)
    let _softSkills__text = [];
    elements = document.getElementById('softSkills_text').innerText;
    element = elements.split("\n");
    element.forEach(element => {
        element.replace(/\s+/g, ' ').trim();
        _softSkills__text.push(element)
    })
    countRow = 0
    maxCountRow = Math.ceil(_softSkills__text.length/arrXPos.length)
    itemsCount = 0

    for (yPos; countRow <= maxCountRow; yPos += yParallax){
        if (itemsCount>_softSkills__text.length) break;
        arrXPos.forEach(element => {
            if (_softSkills__text[itemsCount]!== undefined){
                pdf.text(_softSkills__text[itemsCount], element,yPos)
            }
            itemsCount++
        })
        countRow++;
    }
    pdf.line(_minWidth, yPos, _maxWidth, yPos) // line softSkills end
    pdf.line(_maxWidth * .25, 130, _maxWidth * .25, yPos); // left line
    yPos += 20
    const noteTitle = "NOTE"
    pdf.text(noteTitle, _maxWidth/2 - noteTitle.length/2*3, yPos )
    yPos += 10
    pdf.line(_minWidth, yPos, _maxWidth, yPos) // line Note

    pdf.line(_minWidth, _maxHeight + 15, _maxWidth, _maxHeight + 15) // line Note end
    const sing = "link to CV: mesteriis.github.io"
    pdf.text(sing,_maxWidth/2 - sing.length/2*3,_maxHeight + 25  )

    // for name file
    let d = new Date();
    let curr_date = d.getDate();
    let curr_month = d.getMonth() + 1;
    let curr_year = d.getFullYear();
    let now = curr_date + ':' + curr_month + ":" + curr_year;
    let nameFileToSave = 'Mescheryakov-CV_' + now
    //save pdf
    // pdf.save(nameFileToSave)
    pdf.output('dataurlnewwindow'); // for edit
}

function checkDateIsWorking(dateUnixFormatted) {

    if (isNaN(Date.parse(dateUnixFormatted)) === true) {
        return "date is not valid\nformat UTC or Date.now()"
    }

    dateUnixFormatted = new Date(dateUnixFormatted).toISOString().slice(0, 10).replace(/-/g, '');

    let urlServer = "https://isdayoff.ru/" + dateUnixFormatted;
    let xhr = new XMLHttpRequest();
    xhr.open('GET', urlServer, false);
    xhr.send();
    if (xhr.status !== 200) {
        if (xhr.status === 400 && "100" === xhr.statusText){
            console.log("date is not valid\nformat YYYYMMDD");
            return "date is not valid\nformat YYYYMMDD";
        }
        if (xhr.status === 404 && "101" === xhr.statusText){
            console.log("data not Found")
            return "data not Found";
        }
        // Error, Output Example: 404: Not Found
        console.log(xhr.status + ': ' + xhr.statusText);
        // return xhr.status + ': ' + xhr.statusText;
    } else {
        return xhr.responseText === '0';
    }
}

async function findNextWorkingDay(startDay) {
    if (isNaN(Date.parse(startDay))) {
        return "date is not valid\nformat UTC or Date.now()"
    }
    let date = new Date(startDay);

    let count = 0;
    while (true) {
        date.setDate(date.getDate() + 1)
        const run = await checkDateIsWorking(date);
        if (run) return date;
        count++;
        if (count > 10) {
            return NaN;
        }
    }
    // return date;
}

function saveEvent(){
    let cal_single = ics();
    let nameJob = 'Собеседование на позицию ' + document.getElementById('nameJb').innerText;
    let addressMeeting = document.getElementById('addressMeeting').value;
    let dateMeeting = new Date(document.getElementById('datetimeMeeting').value);
    let dateMeetingEnd = new Date(dateMeeting);

    dateMeetingEnd.setHours(dateMeetingEnd.getHours()+1)

    let title = document.getElementById('nameStr').innerText + ' - Встреча';
    cal_single.addEvent(title, nameJob, addressMeeting, dateMeeting, dateMeetingEnd);
    let x = cal_single.build();
    cal_single.download(title);
    let str = 'mailto:' + document.getElementById('myMail').innerText +'?subject='+nameJob+'&body=Приложите' +
        ' сохраненый файл встречи, я обезательно вам перезвоню по предоставленному контакту и подтвержу встречу, так ' +
        'же вы можете сообщить мне какую то либо информаци, задать вопросы до встречи :)&attachment='
        window.open(str);
}

function switchView(){
    if (document.getElementById('fullLengthOfService').style.display === "")
    {
        document.getElementById('fullLengthOfService').style.display = "none"
    }
    let VisibleFull = document.getElementById('fullLengthOfService').style.display;
    if (VisibleFull === "none") {
        document.getElementById('fullLengthOfService').style.display = "block"
        document.getElementById('cv').style.display = "none"
    } else {
        document.getElementById('fullLengthOfService').style.display = "none"
        document.getElementById('cv').style.display = "block"
    }
}